#!/bin/bash
# Script de configuração automática do Supabase

echo "🌐 CONFIGURAÇÃO AUTOMÁTICA - SISTEMA OBJETIVO"
echo "============================================="
echo ""
echo "📋 PASSOS PARA CONFIGURAR:"
echo ""
echo "1. ✅ Crie projeto no Supabase (https://supabase.com)"
echo "2. ✅ Execute schema.sql no SQL Editor"
echo "3. ✅ Execute seed-data.sql no SQL Editor" 
echo "4. ✅ Configure as variáveis no Discloud:"
echo ""
echo "   VITE_SUPABASE_URL=https://SEU-PROJETO.supabase.co"
echo "   VITE_SUPABASE_ANON_KEY=sua-chave-aqui"
echo ""
echo "5. ✅ Redefine o app no painel do Discloud"
echo ""
echo "🎉 Sistema funcionará com dados persistentes!"
echo ""
echo "👥 USUÁRIOS DE TESTE:"
echo "   Admin: admin@objetivo.com / admin123"
echo "   Professor: professor@objetivo.com / prof123"  
echo "   Pai: pai@objetivo.com / pai123"
echo ""