export const pageTitles: Record<string, string> = {
  dashboard: 'Dashboard',
  notas: 'Notas & Boletim',
  recuperacao: 'Gestão de Recuperação',
  'periodo-letivo': 'Configuração de Período Letivo',
  agenda: 'Agenda',
  materiais: 'Materiais',
  recados: 'Recados',
  notificacoes: 'Notificações',
  perfil: 'Perfil do Aluno',
  usuarios: 'Gerenciar Usuários',
  alunos: 'Gerenciar Alunos',
  turmas: 'Gerenciar Turmas',
  disciplinas: 'Gerenciar Disciplinas',
  relatorios: 'Relatórios',
  'alunos-teacher': 'Meus Alunos',
  'turmas-teacher': 'Minhas Turmas',
  presenca: 'Controle de Presença',
  'provas-tarefas': 'Provas e Tarefas',
  'lancar-notas': 'Lançar Notas',
  permissoes: 'Gestão de Permissões',
  configuracoes: 'Configurações do Sistema',
  auditoria: 'Auditoria e Logs',
  'editar-informacoes': 'Editar Informações da Escola',
  'personalizacao-visual': 'Personalização Visual',
  'personalizacao-sidebar': 'Personalizar Menu Lateral',
  'personalizacao-login': 'Personalizar Tela de Login',
  'dados-importexport': 'Dados - Import/Export',
  manutencao: 'Manutenção do Sistema',
  'configuracao-ajuda': 'Configuração de Ajuda',
  whatsapp: 'WhatsApp Business'
};
